language: node_js
node_js: stable
branches:
  only:
   - dev
before_install:
  - git clone -b dev https://github.com/yidreamc/yidreamc.github.io.git blog-dev
install:
  - npm install
script:
  - npm build
after_success:
  - mkdir -p blog-dev/source/project/todo & cp -r build/* blog-dev/source/project/todo
  - cd ./blog-dev
  - git init
  - git config --global user.name 'yidreamc'
  - git config --global user.email 'yidreamc@gmail.com'
  - git add --all
  - git commit -m "update"
  - git push https://$REPO_TOKEN@github.com/yidreamc/yidreamc.github.io.git master
env:
  global:
    - GH_REF: https://github.com/yidreamc/yidreamc.github.io